"""Add password_hash to empleados

Revision ID: 49f9f4d212f9
Revises: 8a7a7a5dfec9
Create Date: 2026-01-20 17:02:23.074493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f9f4d212f9'
down_revision = '8a7a7a5dfec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'password_hash')
    # ### end Alembic commands ###
