"""Catálogos SAT necesarios para nómina (CFDI 4.0 / Complemento Nómina 1.2).

Los valores se derivan de los XSD y catálogos oficiales publicados por el SAT.
Deben revisarse cada ejercicio fiscal; la última revisión referenciada aquí es 2024–2026.
"""

TIPOS_CONTRATO: dict[str, str] = {
    "01": "Contrato de trabajo por tiempo indeterminado",
    "02": "Contrato de trabajo para obra determinada",
    "03": "Contrato de trabajo por tiempo determinado",
    "04": "Contrato de trabajo por temporada",
    "05": "Contrato de trabajo sujeto a prueba",
    "06": "Contrato de trabajo con capacitación inicial",
    "07": "Modalidad de contratación por pago de hora laborada",
    "08": "Modalidad de trabajo por comisión laboral",
    "09": "Modalidades de contratación donde no existe relación de trabajo",
    "10": "Jubilación, pensión, retiro",
    "99": "Otro contrato",
}

TIPOS_REGIMEN: dict[str, str] = {
    "02": "Sueldos y Salarios e Ingresos Asimilados a Salarios",
    "03": "Jubilados",
    "04": "Pensionados",
    "05": "Asimilados a Salarios - Miembros de las Sociedades Cooperativas de Producción",
    "06": "Asimilados a Salarios - Integrantes de Sociedades y Asociaciones Civiles",
    "07": "Asimilados a Salarios - Miembros de consejos directivos, de vigilancia, consultivos o de cualquier otra índole",
    "08": "Asimilados a Salarios - Comisionistas",
    "09": "Asimilados a Salarios - Honorarios",
    "10": "Asimilados a Salarios - Actividad empresarial",
    "11": "Asimilados a Salarios - Otros",
    "12": "Jubilados o Pensionados",
    "13": "Indemnización o Separación",
    "99": "Otro Régimen",
}

TIPOS_PERCEPCION: dict[str, str] = {
    "001": "Sueldos, Salarios, Rayas y Jornales",
    "002": "Gratificación Anual (Aguinaldo)",
    "003": "Participación de los Trabajadores en las Utilidades PTU",
    "004": "Reembolso de Gastos Médicos, Dentales y Hospitalarios",
    "005": "Fondo de Ahorro",
    "006": "Caja de ahorro",
    "009": "Contribuciones a cargo del trabajador pagadas por el patrón",
    "010": "Premios por puntualidad",
    "011": "Prima de Seguro de vida",
    "012": "Seguro de Gastos Médicos Mayores",
    "013": "Cuotas Sindicales pagadas por el patrón",
    "014": "Subsidios por incapacidad",
    "015": "Becas para trabajadores y/o hijos",
    "019": "Horas extra",
    "020": "Prima dominical",
    "021": "Prima vacacional",
    "022": "Prima por antigüedad",
    "023": "Pagos por separación",
    "024": "Seguro de retiro",
    "025": "Indemnizaciones",
    "026": "Reembolso por funeral",
    "027": "Cuotas de seguridad social pagadas por el patrón",
    "028": "Comisiones",
    "029": "Vales de despensa",
    "030": "Vales de restaurante",
    "031": "Vales de gasolina",
    "032": "Vales de ropa",
    "033": "Ayuda para renta",
    "034": "Ayuda para artículos escolares",
    "035": "Ayuda para anteojos",
    "036": "Ayuda para transporte",
    "037": "Ayuda para gastos de funeral",
    "038": "Otros ingresos por salarios",
    "039": "Jubilaciones, pensiones o haberes de retiro",
    "044": "Ang para gastos de representación",
    "045": "Gastos de representación",
    "046": "Ingreso en acciones o títulos",
    "047": "Alimentación",
    "048": "Habitación",
    "049": "Premios por asistencia",
    "050": "Viáticos",
    "051": "Pagos por gratificaciones, primas, compensaciones, recompensas u otros",
    "052": "Emolumentos Episcopales",
    "053": "Asignaciones para gastos de casa habitación diplomática y gastos de representación",
    "055": "Compensaciones por servicios en el extranjero",
    "056": "Remuneraciones a Socios o Accionistas",
    "057": "Remuneraciones por equiparación con salario al empleador asalariado",
    "058": "Ingresos obtenidos por las personas físicas",
    "059": "Alimentos en bienes",
    "060": "Enajenación de acciones o títulos valor que no se consideran colocados entre el gran público inversionista",
    "061": "Gastos funerales",
    "062": "Diferencial cambiario",
    "063": "Préstamo de casa habitación",
}

TIPOS_DEDUCCION: dict[str, str] = {
    "001": "Seguridad social",
    "002": "ISR",
    "003": "Aportaciones a retiro, cesantía en edad avanzada y vejez",
    "004": "Cuotas sindicales",
    "005": "Aportaciones a fondo de vivienda (INFONAVIT obrero)",
    "006": "Descuento por incapacidad",
    "007": "Pensión alimenticia",
    "008": "Renta",
    "009": "Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores",
    "010": "Pago por crédito de vivienda",
    "011": "Pago de abonos INFONACOT",
    "012": "Anticipo de salarios",
    "013": "Pagos hechos con exceso al trabajador",
    "014": "Errores",
    "015": "Pérdidas",
    "016": "Averías",
    "017": "Adquisición de artículos producidos por la empresa o establecimiento",
    "018": "Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro",
    "019": "Cuotas sindicales",
    "020": "Ausencias (Falta injustificada)",
    "021": "Cuotas obrero patronales",
    "022": "Impuestos locales",
    "023": "Aportaciones voluntarias",
    "024": "Descuentos",
    "025": "Préstamo de la empresa",
    "026": "Descuento por crédito INFONAVIT",
    "027": "Descuento por crédito INFONACOT",
    "028": "Multas",
    "029": "Cuotas de la caja de ahorro",
    "030": "Aportaciones a fondo de ahorro",
    "031": "Otras deducciones",
    "032": "Descuento de nómina",
    "033": "Descuento por préstamo interno",
    "034": "Retardo / Retardos",
}

BANCOS: dict[str, str] = {
    "002": "BBVA Bancomer",
    "006": "Bancomext",
    "009": "Banobras",
    "012": "HSBC",
    "014": "Santander",
    "021": "HSBC México",
    "030": "Bajío",
    "032": "IXE",
    "036": "Inbursa",
    "037": "Interacciones",
    "042": "Mifel",
    "044": "Scotiabank",
    "058": "Banregio",
    "059": "Invex",
    "060": "Bansi",
    "062": "Afirme",
    "072": "Banorte",
    "102": "ABN AMRO",
    "103": "American Express",
    "106": "Bamsa",
    "108": "Tokyo",
    "110": "JP Morgan",
    "112": "Bansí",
    "113": "Vel'sSafi",
    "116": "ING",
    "124": "Deutsche",
    "126": "Credit Suisse",
    "127": "Azteca",
    "128": "Autofin",
    "129": "Barclays",
    "130": "Compartamos",
    "132": "Multiva",
    "133": "Actinver",
    "134": "Walmart",
    "135": "Nafin",
    "136": "Interbanco",
    "137": "HDI Seguros",
    "138": "HDE",
    "139": "UBS Bank",
    "140": "DEL EJÉRCITO",
    "141": "Bimbo",
    "143": "CoDi Valida",
    "145": "Bbase",
    "147": "Bankaool",
    "148": "PagaTodo",
    "149": "Inmobiliario Mexicano",
    "155": "ICBC",
    "156": "Sabadell",
    "166": "BaBien",
    "168": "HIPOTECARIA FED",
    "600": "Monexcb",
    "601": "Bgf",
    "602": "Ipacoll",
    "605": "Valué",
    "606": "Fondeadora",
    "612": "Bansí",
    "613": "Multiva Cbolsa",
    "616": "Finamex",
    "617": "Valore",
    "618": "Única",
    "619": "Mapfre",
    "620": "Profuturo",
    "621": "CB Actinver",
    "622": "Oactin",
    "623": "VWLEASING",
    "626": "CBDEUTSCHE",
    "627": "Zurichvi",
    "628": "SU CASITA",
    "629": "CB Intercam",
    "630": "CB GBM",
    "631": "Intercam Cbo",
    "632": "Finpatria",
    "636": "HDI Seguros",
    "637": "Order",
    "638": "Akala",
    "640": "CB J.P. Morgan",
    "642": "Reforma",
    "646": "STP",
    "648": "Evercore",
    "649": "SKANDIA",
    "651": "Segmenta",
    "652": "Asea",
    "653": "Kuspit",
    "655": "Sofiexpress",
    "656": "Unagra",
    "659": "ASP Integra OPC",
    "670": "Libertad",
    "674": "Arcus",
    "677": "Caja Pop Mexicana",
    "679": "FND",
    "684": "Transfer",
    "685": "Fondo (FIRA)",
    "686": "Invercap",
    "689": "FGENERA",
    "699": "Chivo",
    "706": "Arcus",
    "710": "CoBienestar",
    "722": "Mercado Pago",
    "723": "Cuenca",
    "728": "Spin by OXXO",
    "730": "Nvio",
    "901": "CoDi Valida",
    "902": "TRAN",
}

ENTIDADES_FEDERATIVAS: dict[str, str] = {
    "AS": "Aguascalientes",
    "BC": "Baja California",
    "BS": "Baja California Sur",
    "CC": "Campeche",
    "CL": "Coahuila de Zaragoza",
    "CM": "Colima",
    "CS": "Chiapas",
    "CH": "Chihuahua",
    "DF": "Ciudad de México",
    "DG": "Durango",
    "GT": "Guanajuato",
    "GR": "Guerrero",
    "HG": "Hidalgo",
    "JC": "Jalisco",
    "MC": "Estado de México",
    "MN": "Michoacán de Ocampo",
    "MS": "Morelos",
    "NT": "Nayarit",
    "NL": "Nuevo León",
    "OC": "Oaxaca",
    "PL": "Puebla",
    "QT": "Querétaro",
    "QR": "Quintana Roo",
    "SP": "San Luis Potosí",
    "SL": "Sinaloa",
    "SR": "Sonora",
    "TC": "Tabasco",
    "TS": "Tamaulipas",
    "TL": "Tlaxcala",
    "VZ": "Veracruz de Ignacio de la Llave",
    "YN": "Yucatán",
    "ZS": "Zacatecas",
    "NE": "No encontrada",
}

RIESGOS_PUESTO: dict[str, str] = {
    "1": "Clase I - 0.54355% (riesgo mínimo)",
    "2": "Clase II - 1.13065%",
    "3": "Clase III - 2.59840%",
    "4": "Clase IV - 4.65325%",
    "5": "Clase V - 7.58875% (riesgo máximo)",
}

TIPOS_JORNADA: dict[str, str] = {
    "01": "Diurna",
    "02": "Nocturna",
    "03": "Mixta",
    "04": "Por hora",
    "05": "Reducida",
    "06": "Continuada",
    "07": "Partida",
    "08": "Por turnos",
    "99": "Otra jornada",
}

PERIODICIDAD_PAGO: dict[str, str] = {
    "01": "Diario",
    "02": "Semanal",
    "03": "Catorcenal",
    "04": "Quincenal",
    "05": "Mensual",
    "06": "Bimestral",
    "07": "Unidad obra",
    "08": "Comisión",
    "09": "Precio alzado",
    "10": "Decenal",
    "99": "Otra periodicidad",
}
